// Autogenerated include file

include("node_tests/container/multi.js");
include("node_tests/container/soft_bypass.js");
include("node_tests/control/cable_table.js");
include("node_tests/control/midi.js");
include("node_tests/control/tempo_sync.js");
include("node_tests/control/xfader.js");
include("node_tests/core/gain.js");
include("node_tests/core/oscillator.js");
include("node_tests/core/ramp.js");
include("node_tests/envelope/simple_ar.js");
include("node_tests/filters/convolution.js");
include("node_tests/math/expr.js");
