namespace Utility
{
	inline function rebuildIncludeFile()
	{
		local nodeRootFolder = FileSystem.getFolder(FileSystem.AudioFiles).getParentDirectory().getChildFile("Scripts").getChildFile("node_tests");
		
		Console.assertTrue(nodeRootFolder.isDirectory());
		
		local allTests = FileSystem.findFiles(nodeRootFolder, "*.js", true);
		
		local content = "// Autogenerated include file\n\n";
		
		for(ft in allTests)
		{
			if(ft.toString(1) == "includes")
				continue;
	
			content += "include(\"node_tests/" + ft.getRelativePathFrom(nodeRootFolder) + "\");\n";
			
			
		}
		
		Console.print("New Include file: \n" + content);
		
		
		local includeFile = nodeRootFolder.getChildFile("includes.js");
		includeFile.writeString(content);
	}
}